---
# OS RELEASE: RHEL 6.x, 7.x
# https://launchpad.support.sap.com/#/notes/2235581
# TODO: Check SPS to Operating System
# TODO: Check PPC Architeture variable name


#- debug:
#    msg: "System {{ ansible_distribution }} has uuid {{ ansible_distribution_major_version }} and {{ ansible_distribution_version }}"
#


- name: Check Supported Operating Systems for SAP HANA 1.0
  assert:
    that: 
       (ansible_distribution == "RedHat" and 
         ansible_distribution_major_version == "7" and 
         ansible_distribution_version >= "7.2" and
         ansible_architecture == "x86_64") or
        (ansible_distribution == "RedHat" and 
         ansible_distribution_major_version == "6" and
         ansible_distribution_version >= "6.5" and
         ansible_architecture == "x86_64")
    msg: "This sytem supports HANA {{ sap_hana_version }}"
  when: (ansible_distribution == "RedHat" and 
         sap_hana_version|int == 1)
  ignore_errors: "{{sap_hana_preconfigure_no_strict_version_check|bool}}"


- name: Check Supported Operating Systems for SAP HANA 2.0 
  assert:
    that:
       (ansible_distribution == "RedHat" and 
         ansible_distribution_major_version == "7" and 
         ansible_distribution_version >= "7.2" and
         ansible_architecture == "x86_64") or
       (ansible_distribution == "RedHat" and
         ansible_distribution_major_version == "7" and
         ansible_distribution_version >= "7.3" and
         ansible_architecture == "ppc_le")
    msg: "This sytem supports HANA {{ sap_hana_version }}"
  when: (ansible_distribution == "RedHat" and 
         sap_hana_version|int == 2)
  ignore_errors: "{{sap_hana_preconfigure_no_strict_version_check|bool}}"


...
