- name: 01-network
  hosts: localhost
  
  vars:
          config_variables: azconfig.yml
          config_mount_point: /mnt

  
  vars_files:
          - "{{ config_mount_point + '/' + config_variables }}"

  roles:
         - linux-system-roles.network


