- name: 30-credentials
  hosts: localhost
  vars:
          config_variables: azconfig.yml
          config_mount_point: /mnt

  vars_files:
          - "{{ config_mount_point + '/' + config_variables }}"
  tasks:
    - name: users
      include_tasks: user.yml
#      debug:
#        msg: "{{ item }}"
      with_items: "{{ Credentials }}"
    
