---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distibution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:install'
    - 'role::sap-hana-preconfigure:config'

- import_tasks: installation.yml
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:install'

- import_tasks: configuration.yml
  tags:
    - 'role::sap-hana-preconfigure'
    - 'role::sap-hana-preconfigure:config'
