---
#
# Example file for az config

# Generic Info
version: "20180614"
instance_type: LargeInstance
#sku: "SR92"
#
## SAP Variables
sap_hostname: "azure"
sap_domain: "example.com"
# Required as 7.6 is not officially supported

# Crashdump info
# Input for linux-system-role.kdump possible
# 
# not implemented yet
Crash_dump:
 activate: true
 crash_kernel_low: 80
 crash_kernel_high: 160


# Machine Constraints for verification if system is OK
# not implemented yet
Machine_constraints:
 min_cores: 32
 min_memory: "20tb"


# Networking setup 
#network_provider: nm
network_connections:
       - name: eth0
         interface_name: eth0
         state: up
         type: ethernet
         ip:
                 dhcp4: yes

#
# (NFS shares used for SAP HANA)
nfsStorage:
       - file_system: nfs
#        not implemented yet
         min_size: "112G"
         device: "10.250.21.12:/nfs/share"
         mount: "/remote/foo"
         mount_options: "a,b,c"

# User Accounts 
# (user accounts to be setup, in this example 3-users with SSH public-key files provided - also provides private keys for secure NFS access)
Credentials: 
        - username: hanauser
#          shadow_hash: "sha-512-cipher"
#          ssh-key: "ssh-rsa ..."
#          ssh-private-key: "path/to/private/key/id_dsa"
        - username: somesysuser
          id: 495
          group:
            name: nogroup
            id: 4711
          home_dir: /var/lib/empty
        - username: root
          shadow_hash: "{{ 'root123'|password_hash('sha512') }}"
#          ssh-key: 'ssh-rsa ...'

# Additional packages from local Repo on Config disk
# The additional Packages need to be placed in Packages on the config disk 
# the directory has to be updated with createrepo
# (we can do this in the  playbook if createrepo s added to the image)
# (allows install additional packages on per instance basis, e.g. HPE foundation SW)
Packages:
   rpmlist:
           - PackageKit-gtk3-module

## Is the following still required????
## If yes, we can run a shell command at the end ....
## call: "path/to/executable/file" (if script & overall automation returns success, all good, otherwise failure)

