---

#- name: include os specific vars
  #include_vars: '{{ item }}'
  #with_first_found:
  #  - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
  #  - '{{ ansible_os_family }}.yml'
  #tags:
  #  - 'role::sap-base-settings'
  #  - 'role::sap-base-settings:install'
  #  - 'role::sap-base-settings:config'

- import_tasks: configuration.yml
  tags:
    - 'role::sap-base-settings'
    - 'role::sap-base-settings:config'
