---
######################################
# HANA Default Variables 
#

# Want extensive debugging
debuglevel: 3

# HANA Major and minor version
# These variables are used in all sap-hana scripts
# Thes variables are also set by sap-hana-mediacheck
# Used in SAP Note 2235581 check
sap_hana_version: "2" 
sap_hana_sps: "0"

# set to no,if you want the script to fail, if installed on an unsupported RHEL version according 
# to SAP Note 2235581.
sap_hana_preconfigure_no_strict_version_check: "yes"

# SAP HANA requires minimum packages installed to be supported. These min levels are listed in SAP Note 2235581
# Set to no if you want to ignore these requirements
sap_hana_preconfigure_min_package_check: True

# default Kernel Parameters set in SAP Note 238241
# Additional possible tuning parameters. See SAP Note for details
# The following parameter do not work if communicates with hosts behind NAT firewall
#    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
# Tune these for low latency system replication
#    net.ipv4.tcp_wmem and net.ipv4.tcp_rmem
sap_hana_preconfigure_kernel_parameters: 
    - { name: net.core.somaxconn, value: 4096 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 8192}
    - { name: net.ipv4.ip_local_port_range, value: "40000 61000" }
    - { name: net.ipv4.tcp_timestamps, value: 1 }
    - { name: net.ipv4.tcp_tw_recycle, value: 1 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.ipv4.tcp_syn_retries, value: 8 }
     # Not sure about these .... they were in the old script and not set in tuned
    - { name: kernel.shmmni, value: 65536 }
    - { name: kernel.msgmni, value: 32768 }
    - { name: kernel.sysrq, value: 1 }

# Set the following to false, if you do not want to update the system to the latest release
sap_hana_preconfigure_update: true

# I do not want to boot by default
# You can set this to true if you want to reboot after updating and before configuring the rest
sap_hana_preconfigure_reboot_after_update: false

# Reboot timeout. 
# Large servers may take very long to reboot (Default: 1800s = 30min). 
# you may want to change this according to your environment
sap_hana_preconfigure_reboot_timeout: 1800

###
#
# The following variables are optional 
# If they are defined the user sapadm and sapsys will already be created
# this is necessary for installation of hostagent, but some customers require it at an earlier stage
#
# sap_hana_id_group_sapsys:
# sap_hana_id_user_sapadm:

