- name: 00-getconfig
  hosts: localhost
  
  vars:
          config_mount_src: "LABEL=azconfig"
          config_variables: azconfig.yml
          # config_mount_opts: ro,noauto
          config_mount_opts: noauto, noatime
          config_mount_point: /mnt


  tasks:
          - name: Mount Configuration Directory
            mount: 
                path: "{{ config_mount_point }}"
                src: "{{ config_mount_src }}"
                opts: "{{ config_mount_opts | default(omit) }}"
                state: present

          - name: read configuration info
            include_vars: "{{ config_mount_point + '/' + config_variables }}"

          - name: users
            include_tasks: user.yml
            with_items: "{{ config.Credentials }}"
   roles:
           linux-system-roles.network


